" my vimrc - this file basically initalies dein.vim and loads
" other config files from vim/config + the plugins-subfolder
"======================================================================

if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim " path to dein.vim
endif

call dein#begin(expand('~/.vim/dein')) " plugins' root path
call dein#add('Shougo/dein.vim')

" Let dein.vim handle the rest, and start by loading bundles and
source ~/.vim/config/bundles.vim

" end dein.vim config
call dein#end()

" load the default config and mappings
source ~/.vim/config/settings.vim

" and the configs and mappings for plugins loaded in bundles.vim
source ~/.vim/config/plugins.vim
